name: REST Assured API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:    # Allows manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Display Java and Maven versions
      - name: Verify Java and Maven
        run: |
          java -version
          javac -version
          mvn -v

      # Step 4: Clean and install Maven dependencies
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 5: Run tests
      - name: Run REST Assured Tests
        run: mvn test

      # Step 6: Archive Allure Results
      - name: Archive Allure Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results
